# Generated by Django 3.2.6 on 2024-07-07 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conducteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('site_web', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('horaire', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('photo_conducteur', models.ImageField(upload_to='photo_conducteur/')),
                ('logo_conducteur', models.ImageField(upload_to='logo_garare/')),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='garage_assigne',
        ),
        migrations.DeleteModel(
            name='Garage',
        ),
        migrations.AddField(
            model_name='voiture',
            name='conducteur_assigne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.conducteur'),
        ),
    ]
