# Generated by Django 3.2.6 on 2024-07-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conducteurprofile',
            old_name='is_new_Conducteur',
            new_name='is_new_conducteur',
        ),
    ]
